settings:
  title: 'Status Page'
  url: 'https://status-production.ipsi.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: admin-robotikosakademija-lt # unique identifier
    name: admin.robotikosakademija.lt
    description: 'Admin panel for RA operations.' # default=empty
    url: 'https://admin.robotikosakademija.lt/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: www-robotikosakademija-lt
    name: www.robotikosakademija.lt
    description: 'Main RA site.'
    url: 'https://robotikosakademija.lt'
    method: GET
    expectStatus: 200

  - id: bureliai-robotikosakademija-lt
    name: Būreliai RA
    url: 'https://bureliai.robotikosakademija.lt/'
    method: GET
    expectStatus: 200

  - id: stovyklos-robotikosakademija-lt
    name: Stovyklos RA
    url: 'https://stovyklos.robotikosakademija.lt/'
    method: GET
    expectStatus: 200

  - id: admin-exoclass-com # unique identifier
    name: admin.exoclass.com
    description: 'Admin panel for UK operations.' # default=empty
    url: 'https://admin.exoclass.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: www-clastory-com
    name: www.clastory.com
    description: 'Main UK site.'
    url: 'https://clastory.com'
    method: GET
    expectStatus: 200
